name: Android Pull Request Lint

on:
  push:
    branches-ignore:
      - main
      - 'V-**'
  pull_request:
    types: [ opened, reopened ]
    branches: [ 'V-**' ]

jobs:
  android-lint:
    name: Run Android Lint
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Android Lint
        run: ./gradlew lintDebug
      - uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
          category: lint